[server]
hostname = "0.0.0.0"
port = 53000

[logging]
level = "info" # debug, info, warn, error, critical
console = true # might want to turn it of in CLI mode
file = true
filename = "logs/server.log"

[countdown]
delay = 0
pre_commands = ""
post_commands = ""
