[server]
hostname = "127.0.0.1"
port = 53000

[logging]
console = true
file = true
filename = "logs/server.log"

[client]
name = "NeKz"
model_name = "models/props/food_can/food_can_open.mdl"
current_map = "sp_a1_intro1"
tcp_only = true
color = { r = 1, g = 2, b = 3 }
spectator = false
